language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - python3 main.py
  - if [ $? == 0 ];then
      echo "Build Success. ";
    else
      python3 main.py;
    fi;
