language: python
python:
  - "3.6"
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
before_install:
    - export TZ='Asia/Shanghai'
install:
    - "pip install -r requirements.txt"
script:
  - python3 main.py
